spring.application.name=auth-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Secret
SIGNER_KEY=x4JGZv2Dwv21F9xDin+SO8uy+RCKFtt+15xszMHJBnR5yYEZm9Golm75uBjYaEx3
valid-duration: 3600
refreshable-duration: 36000

spring.zipkin.base-url=http://localhost:9411
spring.sleuth.sampler.probability=1.0